name: fake_process_manager
description: Process Manager for faking processes in tests. Taken from Flutter Tools.
version: 0.1.0+1
homepage: https://github.com/mmcc007/fake_process_manager
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  process: ^4.0.0-nullsafety.2
  tool_base:
    git:
      url: git://github.com/ivan-horchakov/tool_base.git
      ref: master
#  tool_base:
#    path: ../tool_base
  mockito: ^4.1.0
  test: ^1.6.0
dev_dependencies:
  pedantic: ^1.7.0
  